export 'login/login.dart';
export 'onboarding/onboarding.dart';
export 'timetable/timetable.dart';
export 'exams/exams.dart';
export 'assignment/assignment.dart';
export 'fees/fees.dart';
export 'menu/menu.dart';
export 'answer/answers.dart';
export 'exam_sscore/exam-score.dart';